name: Permissions
main: com.nijikokun.bukkit.Permissions.Permissions
depend: [ PermissionsEx ]
version: 1.05
authors: [ t3hk0d3, TheYeti, Nijiko ]
website: www.bukkit.org
description: Compatibility layer between original Permissions and PermissionsEx
